# Generated by Django 3.0.8 on 2020-07-24 01:46

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('modified_at', models.DateTimeField()),
                ('etag', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type_uri', models.URLField()),
                (
                    'context',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='resource_type_context',
                        to='scrud_django.Resource',
                        verbose_name='context resource type',
                    ),
                ),
                (
                    'schema',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='resource_type_schema',
                        to='scrud_django.Resource',
                        verbose_name='schema resource type',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='resource_type',
                to='scrud_django.ResourceType',
                verbose_name='resource type',
            ),
        ),
    ]
