
name: docs

# Only run this when the "master" branch changes
on:
  push:
    branches: [ master ]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: scrud-django
        environment-file: docker/environment-dev.yml
        channels: conda-forge

    - name: Build documentation
      shell: bash -l {0}
      run: |
        make build_doc
    - name: Push documentation to GitHub Pages
      env:
        github_token: ${{ secrets.REPO_TOKEN }}
      run: |
        export REPO_PATH=$(pwd)
        ls
        cd /tmp/
        git clone https://xmnlab:${github_token}@github.com/openteamsinc/scrud-django.git --branch=gh-pages gh-pages
        git config --global user.email "ivan.ogasawara@gmail.com"
        git config --global user.name "Ivan Ogasawara"
        cd gh-pages
        cp -R ${REPO_PATH}/docs/_build/* .
        touch .nojekyll
        git add .nojekyll
        git add .
        git commit --amend -m "Update documentation $(date)"
        git push --force
