
name: docs

# Only run this when the "master" branch changes
on:
  push:
    branches: [ master ]


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Install the pre-release of jupyter book for now until it is "officially" released
    - name: Install Jupyter Book
      run: |
        pip install -r requirements-dev.txt
    # Build the book
    - name: Build the book
      run: |
        make build_doc
    - name: Push documentation to GitHub Pages
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_app: ${{ secrets.GITHUB_APP }}
      run: |
        export REPO_PATH=$(pwd)
        cd /tmp/
        git clone https://${github_app}:${github_token}@github.com/openteamsinc/scrud-django.git --branch=gh-pages gh-pages
        cd gh-pages
        cp -R ${REPO_PATH}/docs/_build/html .
        git add .
        git commit -m "Update documentation"
        git push
