# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    env:
      COMPOSE_FILE: docker/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: scrud-django
        environment-file: docker/environment-dev.yml
        channels: conda-forge

    - name: install dependencies
      shell: bash -l {0}
      run: make develop

    - name: Run pre-commit checking
      shell: bash -l {0}
      run: make pre_commit_check

    - name: Start DB
      shell: bash -l {0}
      run: make start_db

    - name: Test with pytest
      shell: bash -l {0}
      run: make run_tests

    - name: Teardown commands
      shell: bash -l {0}
      run: make stop_db
